WebApplicationASPAuth2/Models/Produit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplicationASPAuth2.Models
{
    public class Produit
    {
        public int Id { get; set; }
        public string  Libelle { get; set; }
        public string  Photo { get; set; }

        public int  CategorieId { get; set; }

        public virtual Categorie Categorie { get; set; }
    }
}

WebApplicationASPAuth2/Controllers/ProduitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationASPAuth2.Models;
using System.IO;
using System.Configuration;

namespace WebApplicationASPAuth2.Controllers
{
    [Authorize] // la page est soumis à une authentifier
    public class ProduitsController : Controller
    {
       
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Produits
        [AllowAnonymous] // permet l'acces à des internautes (users non autorisé)
        public async Task<ActionResult> Index()
        {
            var produits = db.Produits.Include(p => p.Categorie);
            return View(await produits.ToListAsync());
        }

        // GET: Produits/Details/5
        [Authorize(Roles = "ADMIN, SAISIE")]
         public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = await db.Produits.FindAsync(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // GET: Produits/Create
        [Authorize(Roles = "SAISIE")]
        public ActionResult Create()
        {
            ViewBag.CategorieId = new SelectList(db.Categories, "Id", "Designation");
            return View();
        }

        // POST: Produits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Libelle,Photo,CategorieId")] Produit produit, HttpPostedFileBase Photo)
        {
            if (ModelState.IsValid)
            {
                //verfier que le fichier est valide = not null
                //copie l'image danse le dossier des images
                // on met la path dans produit.Photo 
                if(Photo != null && Photo.ContentLength > 0)
                {
                    //var fileName = Path.GetFileName(Photo.FileName);
                    //string dossierImg = ConfigurationManager.AppSettings["PhotosDossier"];
                    //var path = Path.Combine(Server.MapPath(dossierImg), fileName);
                    //Photo.SaveAs(path);
                    //produit.Photo = fileName; 

                    if (Photo != null && Photo.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(Photo.FileName);
                        string dossierImg = ConfigurationManager.AppSettings["photosDossier"];

                        var path = Path.Combine(Server.MapPath(dossierImg), fileName);
                        Photo.SaveAs(path);

                        produit.Photo = fileName;

                    }

                }
                db.Produits.Add(produit);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CategorieId = new SelectList(db.Categories, "Id", "Designation", produit.CategorieId);
            return View(produit);
        }

        // GET: Produits/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = await db.Produits.FindAsync(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategorieId = new SelectList(db.Categories, "Id", "Designation", produit.CategorieId);
            return View(produit);
        }

        // POST: Produits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Libelle,Photo,CategorieId")] Produit produit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produit).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CategorieId = new SelectList(db.Categories, "Id", "Designation", produit.CategorieId);
            return View(produit);
        }

        // GET: Produits/Delete/5
        [Authorize(Roles = "ADMIN")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = await db.Produits.FindAsync(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // POST: Produits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Produit produit = await db.Produits.FindAsync(id);
            db.Produits.Remove(produit);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplicationASPAuth2/Views/Produits/Create.cshtml
@model WebApplicationASPAuth2.Models.Produit

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Produits", FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Produit</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Libelle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Libelle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Libelle, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.CategorieId, "CategorieId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategorieId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategorieId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })*@
            @*Refaire les code for photo *@
            @*<input type="file" onchange="document.getElementById('photoProduit')
                                        .src = window.URL.createObjectURL(this.files[0])"/>*@
            <input name ="Photo" type="file" onchange="document.getElementById('photoProduit').src = window.URL.createObjectURL(this.files[0])
"/>
            <img id="photoProduit" class="img-fluid" alt="photo de fruits"width="200px" height="200px" />

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplicationASPAuth2/Views/Produits/Delete.cshtml
@model WebApplicationASPAuth2.Models.Produit

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categorie.Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie.Designation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplicationASPAuth2/Views/Produits/Details.cshtml
@model WebApplicationASPAuth2.Models.Produit

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Produit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categorie.Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie.Designation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplicationASPAuth2/Views/Produits/Edit.cshtml
@model WebApplicationASPAuth2.Models.Produit

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Libelle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Libelle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategorieId, "CategorieId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategorieId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategorieId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplicationASPAuth2/Views/Produits/Index.cshtml
@model IEnumerable<WebApplicationASPAuth2.Models.Produit>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Categorie.Designation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Libelle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Categorie.Designation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Libelle)
        </td>
        <td>
           @* @Html.DisplayFor(modelItem => item.Photo)*@
            <img alt="photo produit" class="img-fluid" width="100" height="100"src="~/Images/@Html.DisplayFor(modelItem => item.Photo)"/>
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }, new {@class = "btn btn-success"}) 
            @Html.ActionLink("Details", "Details", new { id=item.Id }, new { @class = "btn btn-info" }) 
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>